{"name": "test_generate_content", "status": "broken", "statusDetails": {"message": "NameError: name 'TimeoutException' is not defined", "trace": "browser = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"a31b9407ffb3bbb461e5759d2b15deda\")>\n\n    def test_generate_content(browser: WebDriver):\n        browser.get(LOGIN_PAGE_URL)\n        try:\n>           content_form = WebDriverWait(browser,10).until(\n            EC.presence_of_element_located((By.ID, \"content-form\")) #expected conditions\n            )\n\ncontent_test.py:68: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n/opt/homebrew/lib/python3.11/site-packages/selenium/webdriver/support/wait.py:86: in until\n    value = method(self._driver)\n/opt/homebrew/lib/python3.11/site-packages/selenium/webdriver/support/expected_conditions.py:81: in _predicate\n    return driver.find_element(*locator)\n/opt/homebrew/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:738: in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n/opt/homebrew/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:344: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x1030e0790>\nresponse = {'status': 404, 'value': '{\"value\":{\"error\":\"no such window\",\"message\":\"no such window: target window already closed\\\\...00018556bfa8 _pthread_start + 148\\\\n17  libsystem_pthread.dylib             0x0000000185566da0 thread_start + 8\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nE       from unknown error: web view not found\nE         (Session info: chrome=119.0.6045.123)\nE       Stacktrace:\nE       0   chromedriver                        0x000000010263a004 chromedriver + 4169732\nE       1   chromedriver                        0x0000000102631ff8 chromedriver + 4136952\nE       2   chromedriver                        0x0000000102287500 chromedriver + 292096\nE       3   chromedriver                        0x00000001022602d8 chromedriver + 131800\nE       4   chromedriver                        0x00000001022f3f68 chromedriver + 737128\nE       5   chromedriver                        0x0000000102306fac chromedriver + 815020\nE       6   chromedriver                        0x00000001022c05e8 chromedriver + 525800\nE       7   chromedriver                        0x00000001022c14b8 chromedriver + 529592\nE       8   chromedriver                        0x0000000102600334 chromedriver + 3932980\nE       9   chromedriver                        0x0000000102604970 chromedriver + 3950960\nE       10  chromedriver                        0x00000001025e8774 chromedriver + 3835764\nE       11  chromedriver                        0x0000000102605478 chromedriver + 3953784\nE       12  chromedriver                        0x00000001025daab4 chromedriver + 3779252\nE       13  chromedriver                        0x0000000102621914 chromedriver + 4069652\nE       14  chromedriver                        0x0000000102621a90 chromedriver + 4070032\nE       15  chromedriver                        0x0000000102631c70 chromedriver + 4136048\nE       16  libsystem_pthread.dylib             0x000000018556bfa8 _pthread_start + 148\nE       17  libsystem_pthread.dylib             0x0000000185566da0 thread_start + 8\n\n/opt/homebrew/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py:229: NoSuchWindowException\n\nDuring handling of the above exception, another exception occurred:\n\nbrowser = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"a31b9407ffb3bbb461e5759d2b15deda\")>\n\n    def test_generate_content(browser: WebDriver):\n        browser.get(LOGIN_PAGE_URL)\n        try:\n            content_form = WebDriverWait(browser,10).until(\n            EC.presence_of_element_located((By.ID, \"content-form\")) #expected conditions\n            )\n            assert content_form.is_displayed(), \"Form is missing\"\n>       except TimeoutException:\nE       NameError: name 'TimeoutException' is not defined\n\ncontent_test.py:72: NameError"}, "start": 1700089822566, "stop": 1700089825426, "uuid": "93912727-5aed-4fb4-af11-98bcc264a489", "historyId": "e3de06a7d7307b2522f908a788089df4", "testCaseId": "e3de06a7d7307b2522f908a788089df4", "fullName": "content_test#test_generate_content", "labels": [{"name": "suite", "value": "content_test"}, {"name": "host", "value": "dhcp-128-189-229-206.ubcsecure.wireless.ubc.ca"}, {"name": "thread", "value": "47921-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "content_test"}]}