{"name": "test_generate_content", "status": "broken", "statusDetails": {"message": "NameError: name 'TimeoutException' is not defined", "trace": "browser = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"6fd92063c4f46f2acda37dfc9d3dd3ad\")>\n\n    def test_generate_content(browser: WebDriver):\n        browser.get(LOGIN_PAGE_URL)\n        try:\n>           content_form = WebDriverWait(browser,10).until(\n            EC.presence_of_element_located((By.ID, \"content-form\")) #expected conditions\n            )\n\ncontent_test.py:68: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"6fd92063c4f46f2acda37dfc9d3dd3ad\")>\nmethod = <function presence_of_element_located.<locals>._predicate at 0x10774e8e0>, message = ''\n\n    def until(self, method, message: str = \"\"):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       0   chromedriver                        0x0000000100d86004 chromedriver + 4169732\nE       1   chromedriver                        0x0000000100d7dff8 chromedriver + 4136952\nE       2   chromedriver                        0x00000001009d3500 chromedriver + 292096\nE       3   chromedriver                        0x0000000100a187a0 chromedriver + 575392\nE       4   chromedriver                        0x0000000100a53818 chromedriver + 817176\nE       5   chromedriver                        0x0000000100a0c5e8 chromedriver + 525800\nE       6   chromedriver                        0x0000000100a0d4b8 chromedriver + 529592\nE       7   chromedriver                        0x0000000100d4c334 chromedriver + 3932980\nE       8   chromedriver                        0x0000000100d50970 chromedriver + 3950960\nE       9   chromedriver                        0x0000000100d34774 chromedriver + 3835764\nE       10  chromedriver                        0x0000000100d51478 chromedriver + 3953784\nE       11  chromedriver                        0x0000000100d26ab4 chromedriver + 3779252\nE       12  chromedriver                        0x0000000100d6d914 chromedriver + 4069652\nE       13  chromedriver                        0x0000000100d6da90 chromedriver + 4070032\nE       14  chromedriver                        0x0000000100d7dc70 chromedriver + 4136048\nE       15  libsystem_pthread.dylib             0x000000018556bfa8 _pthread_start + 148\nE       16  libsystem_pthread.dylib             0x0000000185566da0 thread_start + 8\n\n/opt/homebrew/lib/python3.11/site-packages/selenium/webdriver/support/wait.py:95: TimeoutException\n\nDuring handling of the above exception, another exception occurred:\n\nbrowser = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"6fd92063c4f46f2acda37dfc9d3dd3ad\")>\n\n    def test_generate_content(browser: WebDriver):\n        browser.get(LOGIN_PAGE_URL)\n        try:\n            content_form = WebDriverWait(browser,10).until(\n            EC.presence_of_element_located((By.ID, \"content-form\")) #expected conditions\n            )\n            assert content_form.is_displayed(), \"Form is missing\"\n>       except TimeoutException:\nE       NameError: name 'TimeoutException' is not defined\n\ncontent_test.py:72: NameError"}, "start": 1700089405755, "stop": 1700089416131, "uuid": "1a9da041-d479-478f-809c-24733b8eb2e3", "historyId": "e3de06a7d7307b2522f908a788089df4", "testCaseId": "e3de06a7d7307b2522f908a788089df4", "fullName": "content_test#test_generate_content", "labels": [{"name": "suite", "value": "content_test"}, {"name": "host", "value": "dhcp-128-189-229-206.ubcsecure.wireless.ubc.ca"}, {"name": "thread", "value": "46432-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "content_test"}]}